### ISSUE TITLE
GUI popup displays strategies for one solver and behaviors for another.

### ISSUE THREAD

**Issue by mdnahas** [gambitproject/gambit#319] opened 2022-08-29 15:10 UTC
I loaded a file containing the "simple poker game" which had moves labeled.

When I click on the calculator icon ("compute nash equilibria") and select "compute all Nash Equilibria", the popup window did not use the move labels.  The top row of the window was:
1:11 | 1:12 | 1:21 | 1:22 | 2:1 | 2:2

After hitting "ok", the display of equilibria in the bottom of the split main window did use the move labels.
1:R | 1:F | 2:R | 2:F | 1:M | 1:P

This only seems to happen with "compute all nash equilbria".

**Comment by mdnahas** [comment] 2022-08-29 15:22
**This may be a bigger issue than just display.**

The pop-up window says:

| # | 1:11 | 1:12 | 1:21 | 1:22 | 2:1 | 2:2  |
|--|--|--|--|--|--|--|
| 1 | 1/3  | 2/3 | 0 | 0 | 2/3 | 2:2 |

While the bottom of the split screen says:

| # | 1:R | 1:F | 2:R | 2:F | 1:M | 1:P|
|--|--|--|--|--|--|--|
| 1 | 1 | 0 | 1/3 | 2/3 | 2/3 | 1/3 |

There is no "1" in the equilibrium in the popup window, but there is a "1" in the bottom of the split screen.

Given that and the labels, it makes me think that the bottom of the split screen is not being calculated the same way as the data in the popup window.

**Comment by mdnahas** [comment] 2022-08-29 15:52
I think 2 things are happening here.

1) The EnumMixedSolver is producing bad output   (See #320  )
2) The GUI is replacing that bad output with something else in the bottom split window.  

This issue is for the second item.  It is very worrying that the bad output is being replaced somehow!

**Comment by mdnahas** [comment] 2022-08-29 17:54
It looks like the issue is a "behavior" vs. a "strategy".  One solver is producing mixed strategies and another is producing behaviors (probabilities for each move from an information set).

Still, the GUI is displaying a strategy in the output for Enum Mixed Solver, but displaying a behavior for other ones.

**Comment by tturocy** [comment] 2022-09-06 14:30
This is essentially a duplicate of #320 conceptually.  The GUI displays the appropriate representation of the strategy profile given the representation of the game.  This is in fact not a bug, but is precisely the correct and transparent way to do it.

**Closed by tturocy** 2022-09-06 14:30 UTC
