### ISSUE TITLE
Python tests and "players.add" method are failing on  OS X El Capitan 10.11.4

### ISSUE THREAD

**Issue by llinfeng** [gambitproject/gambit#173] opened 2016-04-01 00:11 UTC
While the command-line tools are working well on my OS X machine using the sample games, the Python interface keeps failing me.

1. After following instruction kindly given in the hyperlink that follows, I was able to `import gambit` in Python. However, after properly fixing the "nose" package, executing the `nosetests` command gives me **Segmentation fault: 11**;
http://gambit.sourceforge.net/gambit15/build.html#building-the-python-extension 

2. While I was trying to follow the tutorial and try to run the following code, the Python instance will *quit unexpectedly* every time when it tries to execute the last line, featuring the `player.add` method:
```
    import gambit

    g = gambit.Game.new_tree()
    print len(g.players)
    g.title = "A simple poker example"
    print g.title
    print g

    p = g.players.add("Alice")
```
The error message left in the Terminal is again "**Segmentation fault: 11**".

A similar "Segmentation fault: 11" problem had been solved in the following posting for previous releases of OS X.  [https://shellzero.wordpress.com/2014/08/31/python-interpreter-segmentation-fault-11-on-osx/] I am wondering if Apple had again made some crazy changes.

Thank you!

-Linfeng

**Comment by tturocy** [comment] 2016-04-04 16:22
Thank you for this.  Not surprisingly I cannot reproduce this on any system I have; I do not currently have El Capitan installed anywhere.

I think the detail of the linked article is probably a red herring, but I suspect it may be correct that there is some problem with linking against different libraries.

For completeness, could you please provide the versions of Python as well as Cython used to build this?  Ideally a full log of the output of the build and install stages from setup.py would be helpful as well.

**Comment by tturocy** [comment] 2016-05-03 15:03
@llinfeng and others, I have had an opportunity to investigate this further.  It is definitely *not* related to the linked article.  It does seem to be a strange compiler bug (or feature) pertaining to C++ exceptions which do not have explicitly-defined constructors.

I have pushed up a potential fix as the branch master_explicitexception .

I would value any feedback (from @llinfeng or others) as to whether this works for you on El Capitan, and/or whether it creates any unexpected behaviour changes elsewhere.

**Comment by llinfeng** [comment] 2016-05-14 19:44
Hi @tturocy, I am happy to test out, but I don't find the branch "`master_explicitexception`" from the following url: https://github.com/gambitproject/gambit/branches/all

Which repo were you referring to? Thank you!

**Comment by tturocy** [comment] 2016-05-15 07:54
@llinfeng Many thanks.  I have already merged the change into master

**Closed** 2016-06-07 15:27 UTC
