### ISSUE TITLE
gambit-logit Error: Dereferencing an invalidated object

### ISSUE THREAD

**Issue by luke777** [gambitproject/gambit#164] opened 2015-10-08 14:08 UTC
I am getting an "Error: Dereferencing an invalidated object" when using the latest code from github.  The error does not occur when I build using the gambit-14.1.0 code distribution.  I am running ubuntu 14.04.

./gambit-logit contrib/games/coord3.nfg
Compute a branch of the logit equilibrium correspondence
Gambit version 15.0.0, Copyright (C) 1994-2014, The Gambit Project
This is free software, distributed under the GNU GPL

0.000000Error: Dereferencing an invalidated object

**Comment by tturocy** [comment] 2015-10-08 15:10
I'm not able to reproduce this.

Can you provide the output of the configure script?

Also, it is unorthodox that you seem to be running this from the current directory?

**Comment by luke777** [comment] 2015-10-08 16:45
The output of the configure script is below.  I am getting a warning.  I ran it with the  --disable-gui option.  Before running it, I ran "make clean"

**********/gambit$ ./configure --disable-gui > output.txt
**********/gambit/missing: Unknown `--is-lightweight' option
Try `************/gambit/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing



checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether we are building for a Win32 host... no
checking for bcmp... yes
checking for srand48... yes
checking for drand48... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/Makefile
config.status: creating contrib/scripts/Makefile
config.status: creating contrib/scripts/enumpoly/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by luke777** [comment] 2015-10-08 16:54
I am getting the same problem with all the *.nfg files I try.  The *.efg files work as expected unless I use the -S flag, in which case they produce the same error as the nfg files.

**Comment by tturocy** [comment] 2015-10-09 06:01
The config setup looks fine. Which is unfortunate in a way.  At the moment, I still can't reproduce it, and there aren't any hints so far as to what could be the problem.

You didn't mention why it was you were running the binary from the current directory?

**Comment by luke777** [comment] 2015-10-09 13:12
Running from the current directory seemed convenient.  I get the same results if I run it from a different directory.  

~$ /usr/local/bin/gambit-logit ~/code/gambit/contrib/games/coord3.nfg 
Compute a branch of the logit equilibrium correspondence
Gambit version 15.0.0, Copyright (C) 1994-2014, The Gambit Project
This is free software, distributed under the GNU GPL

0.000000Error: Dereferencing an invalidated object

**Comment by luke777** [comment] 2015-10-29 14:00
I am no longer experiencing this problem.  I am not sure what was causing it.  I updated my system from ubuntu 14.04 to 15.10 and now can no longer reproduce it.

**Comment by tturocy** [comment] 2015-10-29 14:56
This issue is no longer being experienced by the OP.  While there could be some underlying problem, this plus the inability to reproduce elsewhere suggests most likely explanation is simply build skew.  Closing unless/until it is replicated elsewhere.

**Closed by tturocy** 2015-10-29 14:56 UTC

**Comment by fhauschultz** [comment] 2018-10-24 12:32
Hi

I get the same error as OP. I am on a server running Ubuntu 16.04.

/home/fredph/gambit/bin/gambit-logit  /home/fredph/gambit-15.1.0/contrib/games/2x2x2.nfg
Compute a branch of the logit equilibrium correspondence
Gambit version 15.1.0, Copyright (C) 1994-2014, The Gambit Project
This is free software, distributed under the GNU GPL
0.000000Error: Dereferencing an invalidated object

Gambit works fine if I run any other solution method. I get the same error whether I run gambit 15 or gambit 16.

**Comment by fhauschultz** [comment] 2018-10-24 13:07
Update: I noticed OP had no problems in Gambit 14.1.1. I just installed 14.1.1. and it also works fine for me there. So it could look like I have the same problem as OP.
