### ISSUE TITLE
Contingencies are not accessible from Game object

### ISSUE THREAD

**Issue by yasuiniko** [gambitproject/gambit#328] opened 2023-02-05 05:15 UTC
I am using Python 3.9.6 and macOS 13.0.1. When I read a game and try to access its contingency property, I get the following error:

```zsh
File "pygambit/lib/game.pxi", line 263, in pygambit.lib.libgambit.Game.contingencies.__get__
AttributeError: module 'pygambit' has no attribute 'gameiter'
```

This seems like a simple problem but I'm not sure how to fix it. Does anyone have any insight? Did I install `pygambit` incorrectly?

### To reproduce:
```zsh
python3 -m venv test_gambit
source test_gambit/bin/activate
python3 -m pip install pygambit
python3 test_read_game.py
```

```python3
## test_read_game.py
import pygambit as gambit

nfg = """
NFG 1 R "sw95_2"
{ "0" "1" } { 3 3 }
75.0 75.0 70.0 40.0 70.0 45.0 40.0 70.0 15.0 15.0 60.0 100.0 45.0 70.0 100.0 60.0 0.0 0.0
"""

def main():
    nfg_fn = "game_file.nfg"
    with open(nfg_fn, 'w') as f:
        f.write(nfg)
    
    game = gambit.Game.read_game(nfg_fn)
    print(game.contingencies)

if __name__ == "__main__":
    main()
```

**Comment by tturocy** [comment] 2023-02-06 16:58
Duplicate of #306.

**Closed by tturocy** 2023-02-06 16:58 UTC
