### ISSUE TITLE
Gambit python interface freezes while trying to solve game using gambit.nash.ExternalLogitSolver()

### ISSUE THREAD

**Issue by ShashankGargeshwari** [gambitproject/gambit#226] opened 2017-10-28 21:31 UTC
I am simulating an artificial world where agents take decisions in a game theoretic manner. I use gambit construct a game table based on certain criteria, and solve it. Below is a code excerpt showing the actual solve method being called (**Note:**  `g` is the game in which the game table is stored)  

    solver = gambit.nash.ExternalLogitSolver()
    solution = solver.solve(g)  

The program freezes at this point with no error or exception. I checked whether it is because of too much load on the solver, but it is not the case (It sometimes even freezes for 2 Player-9 choices games)

Breaking operation on PyCharm throws this message (It always seems to stall at this exact same point):
    
    File "build/bdist.linux-x86_64/egg/gambit/nash.py", line 207, in solve
    File "build/bdist.linux-x86_64/egg/gambit/nash.py", line 65, in _parse_output
    KeyboardInterrupt

**P.S.:** Is there any way we can get a "log file" of the gambit module running?

**Comment by tturocy** [comment] 2017-10-30 19:16
It is helpful to provide a complete example that can reproduce the issue.

Because you are calling an external program, it is always going to break in the same place (waiting for output from the program), so that is not particularly informative.

You can run the command-line program directly and get live output from it - that will help identify the situation.  However, again, a complete example that shows the issue is needed to be able to help at all.

**Comment by ShashankGargeshwari** [comment] 2017-11-04 18:36
Short Version : It Seems to happen whenever the payoffs are set to large values like -99999 / -9999 / +1000 etc. The crashes pretty much vanished after I scaled down the payoffs to be less than 100 in magnitude. It does still stall now and then, I'll get back with more info in a couple of days. 

Long Version : https://github.com/ShashankGargeshwari/Fairness/tree/7eeda7df16608cba9f18552c41a97ab0cc4d4558
This version contains the crash prone software, Run game.py to see it in action.

**Comment by tturocy** [comment] 2017-11-05 05:45
Yes, I will need to see the smallest example that demonstrates the Gambit issue.  You will understand that it is completely impractical for me to debug someone else's application with all of the dependencies etc required.

**Comment by tturocy** [comment] 2021-07-07 13:04
No file was ever provided, so closing - it can be re-opened if an example can be given.

**Closed by tturocy** 2021-07-07 13:04 UTC
