### ISSUE TITLE
Is gambit thread safe?

### ISSUE THREAD

**Issue by baskuit** [gambitproject/gambit#333] opened 2023-04-10 10:17 UTC
I incorporate the Gambit source for enummixed solver in my project, which is multithreaded. I use a janky wrapper which I will paste below:

    template <class TypeList>
    Gambit::Game build_nfg(
        typename TypeList::MatrixReal &row_payoff_matrix,
        typename TypeList::MatrixReal &col_payoff_matrix)
    {
        Gambit::Array<int> dim(2);
        dim[1] = row_payoff_matrix.rows;
        dim[2] = row_payoff_matrix.cols;
        Gambit::GameRep *nfg = NewTable(dim);
        Gambit::Game game = nfg;
        Gambit::StrategyProfileIterator iter(Gambit::StrategySupportProfile(static_cast<Gambit::GameRep *>(nfg)));
        for (int j = 0; j < row_payoff_matrix.cols; ++j)
        {
            for (int i = 0; i < row_payoff_matrix.rows; ++i)
            {
                (*iter)->GetOutcome()->SetPayoff(1, std::to_string(row_payoff_matrix.get(i, j)));
                (*iter)->GetOutcome()->SetPayoff(2, std::to_string(col_payoff_matrix.get(i, j)));
                iter++;
            }
        }
        return game;
    }

    template <class TypeList>
    void solve_bimatrix(
        typename TypeList::MatrixReal &row_payoff_matrix,
        typename TypeList::MatrixReal &col_payoff_matrix,
        typename TypeList::VectorReal &row_strategy,
        typename TypeList::VectorReal &col_strategy)
    {
        Gambit::Nash::EnumMixedStrategySolver<double> solver;
        Gambit::Game game = build_nfg<TypeList>(row_payoff_matrix, col_payoff_matrix);
        Gambit::shared_ptr<Gambit::Nash::EnumMixedStrategySolution<double>> solution = solver.SolveDetailed(game);
        Gambit::List<Gambit::List<Gambit::MixedStrategyProfile<double>>> cliques = solution->GetCliques();
        if (!cliques.empty() && !cliques[1].empty())
        {
            Gambit::MixedStrategyProfile<double> joint_strategy = cliques[1][1];
            typename TypeList::Real is_interior = 1.0;
            for (int i = 0; i < row_payoff_matrix.rows; ++i)
            {
                row_strategy[i] = static_cast<typename TypeList::Real>(joint_strategy[i + 1]);
                is_interior *= 1 - row_strategy[i];
            }
            for (int j = row_payoff_matrix.rows; j < row_payoff_matrix.rows + row_payoff_matrix.cols; ++j)
            {
                col_strategy[j - row_payoff_matrix.rows] = static_cast<typename TypeList::Real>(joint_strategy[j + 1]);
                is_interior *= 1 - col_strategy[j];
            }
        }
        else
        {
            BimatrixGame<TypeList> matrix_game(row_payoff_matrix, col_payoff_matrix);
            matrix_game.solve(row_strategy, col_strategy);
        }
        delete game;
    }

I've been getting some fatal memory errors that take a while to happen in debug mode since otherwise the code is pretty reliable.

`malloc(): unsorted double linked list corrupted` which I've yet to reproduce and
`free(): corrupted unsorted chunks` which just happened as a result of the `delete game;` line above, specifically:

    ~shared_ptr() 
    {
      if (--*m_count == 0) {
        delete m_ptr; // Exception occurs here
        delete m_count;
      }
    }

I have not gotten these errors in the single threaded version of my application, which is why I ask.

I know you guys have been STL-izing the code lately so this issue might be fixed.

**Comment by tturocy** [comment] 2023-04-10 11:39
Almost surely not.  The core code is more than 20 years old, and threading was not a thing.

I would suggest trying 'master' if you have not done so already.  For example ``Gambit::shared_ptr`` has been removed in favour of ``std::shared_ptr`` in the handful of places it was used.  Also - I can't tell whether it's the problem or not, but assigning the output of ``NewTable`` to a ``GameRep`` is probably asking for trouble.  There are some circumstances where a game doesn't get deleted (there is a candidate fix in testing in a branch), but arguably that's a lot better than circumventing the system (so likewise ``delete game`` is not a good idea...!)

**Comment by baskuit** [comment] 2023-04-10 16:50
@tturocy 
Maybe I should have clarified that the wrappers that create a game are run in each thread independently. Nothing above is a shared resource.
I'm going to repo (as as submodule to my project) very soon, so this might all be moot.  Also I'm only mostly positive that returning the shared_ptr (gambit or stl) by value is the correct thing to do.

> Also - I can't tell whether it's the problem or not, but assigning the output of NewTable to a GameRep is probably asking for trouble.

What should I be doing instead if I want to create a game using a matrix of `double`? I recall I tried to mirror the protocol of enummixed.cc as much as possible. Surely there has to be something better than this string conversion:

    for (int j = 0; j < row_payoff_matrix.cols; ++j)
    {
        for (int i = 0; i < row_payoff_matrix.rows; ++i)
        {
            (*iter)->GetOutcome()->SetPayoff(1, std::to_string(row_payoff_matrix.get(i, j)));
            (*iter)->GetOutcome()->SetPayoff(2, std::to_string(col_payoff_matrix.get(i, j)));
            iter++;
        }
    }

**Comment by tturocy** [comment] 2023-04-14 09:37
It looks like there's more than one thing going on here.

First, I was looking at this:
```
    Gambit::GameRep *nfg = NewTable(dim);
    Gambit::Game game = nfg;
```

I think this might lead to a double-deletion.  ``NewTable`` returns a ``Game``, which is a smart pointer.  You're taking the raw pointer out of it, and then assigning it to a new smart pointer.  But then the first smart pointer gets destructed, which *ought* to take the ``GameRep`` with it.  (There's a known issue with this as mentioned for which there's a candidate fix, but that's what the behaviour is supposed to be.)  So that's definitely wrong - if Gambit's implementation were correct, this would *definitely* crash, but it's possible that it doesn't because Gambit's implementation isn't quite correct as released.

Then relatedly, in the final line, because ``game`` is a smart pointer, you shouldn't ``delete`` it - the smart pointer handles it.  So that also would lead to a double-deletion if Gambit's implementation were correct.

However, neither of those deal with the memory error in Gambit::~shared_ptr.  However this is probably moot as that code isn't there anymore - it now uses std::~shared_ptr.  However this is also happening after a possible corruption to the memory from the above, so hard to know.

Finally on numbers - this is by design.  All payoffs must be rational numbers.  This is for two reasons: First, in two player games, sets of equilibria can be expressed exactly in rational numbers.  Second, the implementation of numerical data in games ensures round-trip in representation - so someone can input "10.1" and it comes back as "10.1" and not "101/100" or another representation.  These are Good Things - when we implemented this a lot of problems people had with unexpected solutions to games went away.  The implementation requires calling code to make a decision about how to represent payoffs.  There is a strand (not yet pushed to the public repo) which improves the way Gambit::Number is used to make the process a bit more explicit and readable - but doesn't change that basic concept.

**Closed** 2023-04-28 18:38 UTC
